name: CI

on:
  push:
    branches: 
          - master
          - development
  pull_request:
    branches:
          - master
          - development

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: KingGame
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
    
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run a build
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test
